### ISSUE TITLE
Doesn't solve "classic" 5x8 Tetromino puzzles

### ISSUE THREAD

**Issue by chriscamacho** [adolfintel/tetrispuzzlesolver#1]
using the following pieces and quantities

I * 2,  O * 2,  T * 2,
L * 1,  J * 1, S * 1, Z * 1

There are numerous ways to fit these pieces into a
5x8 grid - your algorithm claims its impossible!

     LSIIIIOO
     LSStttOO
     LLSTtJJJ
     OOTTTZZJ
     OOIIIIZZ

A classic 5*8 using these tiles

**Comment by adolfintel** [comment]
Looks like it works for me. Maybe you inputted the wrong data? 

![2017-11-21 18_27_42-federico dossena - iridium](https://user-images.githubusercontent.com/16307689/33087141-05bf3ce8-ceea-11e7-9d90-40e233583c0f.png)

**Comment by chriscamacho** [comment]
working down the input boxes I input

5,8,2,2,2,1,1,2,1

I'm using the jar from your website

**Comment by chriscamacho** [comment]
doh, i saw what I did.... *sigh* sorry...

**Comment by adolfintel** [comment]
You have an error, it's 5,8,2,2,2,1,1,**1**,1

**Comment by adolfintel** [comment]
No problem :)
It happens
